# Generated by Django 5.2.6 on 2025-09-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial_images/')),
                ('comment', models.TextField(max_length=500)),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
    ]
